#ifndef __TLS_COM_H__
#define __TLS_COM_H__

typedef enum __TLS_RESULT 
{
	TLS_RESULT_S_OK = 0,
	TLS_RESULT_S_CONTINUE,
	TLS_RESULT_E_FAIL = -0x10000,
	TLS_RESULT_E_INVALID_PARAM,
	TLS_RESULT_E_INVALID_DATA,
	TLS_RESULT_E_INVALID_HANDLE,
	TLS_RESULT_E_INVALID_INDEX,
	TLS_RESULT_E_INVALID_ADDRESS,
	TLS_RESULT_E_INVALID_PORT,
	TLS_RESULT_E_NOTFOUND,
	TLS_RESULT_E_NOTSUPPORT,
	TLS_RESULT_E_NOTREADY,
	TLS_RESULT_E_NO_INSTANCE,
	TLS_RESULT_E_ALLOCATE,
	TLS_RESULT_E_RESOURCE,
	TLS_RESULT_E_SOCKET,
	TLS_RESULT_E_BAD_STATUS,
	TLS_RESULT_E_BAD_RESULT,
	TLS_RESULT_E_TIMEOUT,
}TLS_RESULT;

#define TlsResultOk(a)	((a) >= 0)
#define TlsResultFail(a) (a < 0)

#define TLS_UNUSERD_PARAM(a)		(void)(a)

#define __TLSDBG(fmt, ...) printf("[%s,%d]"fmt"\n", __func__, __LINE__, ##__VA_ARGS__);
#define __ENSTACK()		printf("--->[%s].\n", __func__);
#define __OUTSTACK()	printf("<---[%s].\n", __func__);

#define TLS_MAX_STR_SIZE			(256)
#define TLS_MAX_IP_SIZE				(32)

#define TLS_TRANSMIT_BUFF_COUNT		(1024)
#define TLS_RECEIVE_BUFF_COUNT		(1024)

#define TLS_QUEUE_COUNT				(8)	
#define TLS_BUFF_SIZE				(2048)
#define TLS_BUFF_TYPE_TX			(0)
#define TLS_BUFF_TYPE_RX			(1)

#define TLS_REGISTER_OK				(0)
#define TLS_REGISTER_FAIL			(-1)

#define TLS_VSOA_NAME_SISE			(32)
#define TLS_VSOA_MAX_STR_SIZE		(256)

#define TLS_VSOA_URL_COUNT			(16)

enum __TLS_QUEUE_PRIORITY
{
	TLS_QUEUE_PRI_0 = 0,
	TLS_QUEUE_PRI_1,
	TLS_QUEUE_PRI_2,
	TLS_QUEUE_PRI_3,
	TLS_QUEUE_PRI_4,
	TLS_QUEUE_PRI_5,
	TLS_QUEUE_PRI_6,
	TLS_QUEUE_PRI_7,
	TLS_QUEUE_MAX_COUNT,
};

enum __TLS_QUEUE_COUNT
{
	QUEUE_PRI_0_COUNT = 1536,
	QUEUE_PRI_1_COUNT = 1024,
	QUEUE_PRI_2_COUNT = 1024,
	QUEUE_PRI_3_COUNT = 1024,
	QUEUE_PRI_4_COUNT = 1024,
	QUEUE_PRI_5_COUNT = 640,
	QUEUE_PRI_6_COUNT = 512,
	QUEUE_PRI_7_COUNT = 128,
};

enum __TLS_TRANSMODE
{
	TLS_UDP = 0,
	TLS_VSOA,
};

#endif // __TLS_COM_H__
