[formats]
simple  = "%m%n"
normal  = "%d.%ms %m%n"
[rules]
my_cat.*	"/var/log/tls.log", 100KB * 4 normal
# my_cat.*	"./tlslog/tls.log", 100KB * 4 ~ "tls.log.#r" 
# my_cat.*	"./tls.%d(%F).log", 100KB * 4 
